# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 451d2951642f3ee2ebda32ad1c06afd661f33e0bfd6d0c50172515063acbfb40654109959c3abd874adc53eaa800ac0820f750c8ec64a24083a0fda3e9eb40ca

test:
  secret_key_base: 5f9782d73d1d1d249439b71e970ce36e0181064065ea2308349ef45f321893955eb3dd145be37749758da24d8b0d0b16d908607c0ba48edce3aec960abeb4cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
